# Generated by Django 3.0.2 on 2020-02-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20200218_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='done',
        ),
        migrations.RemoveField(
            model_name='list',
            name='task',
        ),
    ]
