# Generated by Django 3.0.2 on 2020-02-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_auto_20200226_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=200)),
                ('exec', models.BooleanField(default=False)),
                ('classify', models.BooleanField(default=False)),
            ],
        ),
    ]
